### ISSUE TITLE
get_account_dump [Python] giving TypeError: invalid exception object

### ISSUE THREAD

**Issue by JatzCracker** [raid-toolkit/raid-toolkit-sdk#74]
Error as described in title. All other API seem to be working as intended. 

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 380, in _set_state
    _copy_future_state(other, future)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 356, in _copy_future_state
    dest.set_exception(_convert_future_exc(exception))
TypeError: invalid exception object

Is anyone else receiving this error? I tried with latest build as well as latest pre-release with same result.

Thanks for such great work by the way !!

**Comment by WOROTH** [comment]
Confirmed NOT.
Every existing API commands are perfectly operating.

**Comment by JatzCracker** [comment]
I get the error even when I use the example script provided (which worked previously). 

It's only for the full account dump as well. All others work perfectly.

**Comment by JatzCracker** [comment]
Update - setting up a solo Arena team did not fix it. 

Group arena is a long way off for this account.
